### ISSUE TITLE
Tool fails on Kali 4.9.0-kali4-amd64

### ISSUE THREAD

**Issue by pieterhouwen** [th3gundy/BH-Downloader#1]
I get this output when trying to download any BH briefing:

root@myprecious:~/BH-Downloader# python bh-downloader.py https://www.blackhat.com/us-16/briefings.html
Traceback (most recent call last):
  File "bh-downloader.py", line 8, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
root@myprecious:~/BH-Downloader# 

Am I missing a dependency or something?

**Comment by th3gundy** [comment]
Hi,

its look like python BeautifulSoup library error.

try;
`pip install --upgrade beautifulsoup4`
`pip install --upgrade html5lib`

**Comment by pieterhouwen** [comment]
Awesome, that fixed it. Thank you!
